### ISSUE TITLE
build/bootstrap/make.com broken on NixOS

### ISSUE THREAD

**Issue by necrophcodr** [jart/landlock-make#1]
It would appear that the included `build/boostrap/make.com` file does not work out of the box as perhaps is intended. Instead, the following issue occurs (using `strace` for clarity):

```
# strace -f ./build/bootstrap/make.com 
execve("./build/bootstrap/make.com", ["./build/bootstrap/make.com"], 0x7ffc18f11948 /* 88 vars */) = -1 ENOEXEC (Exec format error)
strace: exec: Exec format error
+++ exited with 1 +++
```

**Comment by jart** [comment]
Chances are you're using WSL. Try disabling binfmt_misc. If that doesn't work, try `bash -c build/bootstrap/make.com`

**Comment by necrophcodr** [comment]
> Chances are you're using WSL. Try disabling binfmt_misc. If that doesn't work, try `bash -c build/bootstrap/make.com`

I'm not using WSL, but I do have binfmt_misc enabled for aarch64, and will try disabling that. Running `bash -c build/bootstrap/make.com` results in:

```
-> % bash -c build/bootstrap/make.com
make.com: *** [Makefile:41: o//pkg/main_0.o] SIGSEGV (core dumped)
```

**Comment by jart** [comment]
I'm sorry we don't support aarch64 on Linux right now.

**Comment by necrophcodr** [comment]
> I'm sorry we don't support aarch64 on Linux right now.

That's okay, I'm not running it on aarch64 either. I'm using NixOS on an x86-64-based computer. I've disabled binfmt_misc entirely from the system and rebooted, and the result is the same. No change.
However, I did try it in a virtual machine, and I've noticed that the binary has changed, and now works correctly. So thanks for fixing it!

**Comment by jart** [comment]
Excellent. I've been doing a lot of work the past day to polish the tool. Glad to hear it fixed itself. Enjoy it!
